### ISSUE TITLE
Two questions on MOML code

### ISSUE THREAD

**Issue by zhaozj89** [Baijiong-Lin/MOML#1]
Thanks very much for sharing this work. I have two questions when executing this code. 

1. When I ran the following command:

`python ./MTL/moml_office.py --gpu_id 1 --model DMTL --dataset office-31 --batchsize 64 --MGDA --dataroot  /path/to/office-31`

It reported the following error:

`TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'` on line 84 `p_fast = p - 1e-4 * grads[g_index]`.

It seems that there are some inputs are not used for gradient calculation on line 80 `grads = torch.autograd.grad(loss, (meta_model.parameters()), create_graph=True, allow_unused=True)`. What could be that?

2. Same for `python ./MTL/moml_office.py --gpu_id 1 --model DMTL --dataset office-31 --batchsize 64 --MGDA --dataroot  /path/to/office-31`,

I saw that there are four data modes used: `train`, `val`, `test`, `trval`. What are their purposes? It seems that some parts of the network are trained purely by gradient descent with `train`, while the head is trained by MOML with `val` and `trval`. Am I right? 

 Thanks!

**Comment by Baijiong-Lin** [comment]
Thanks for your inerest in our work.

1. This error is because there are some parameters in the model are unused in the forward process and they do not have gradients in the backward or torch.autograd.grad() process. Actually, these unused parameters are in the linear layer of the ResNet network (pls see [here](https://github.com/Baijiong-Lin/MOML/blob/main/MTL/model/resnet.py#L155)). We have fixed this bug.

2.  Firstly, there is no intersection between ``train`` and ``val``. ``trval`` is the union of ``train`` and ``val``. In fact, ``trval`` is equivalent to the conventional training dataset. Secondly, in our MOML method, we need to use ``train`` data to solve the LL subproblem, then use ``val`` data to solve the UL subproblem to calculate the optimal hyper-parameters, and finally use the ``trval`` data to update the model parameters by fixing the hyper-parameters. Thirdly, all the baselines are trained with the ``trval`` data and the reported results of all methods (baselines and our MOML) are the best results on the ``test`` data.

**Comment by zhaozj89** [comment]
Thanks for the reply. Now is clear to me. Good work!
